storage:
  type: 'YML'

skill-execution:
  pattern-size: 3
  pattern-types:
    - LEFT_CLICK
    - RIGHT_CLICK
  default-execution-group: 'default'
  execution-groups:
    default:
      max-equipped-skills: 4
      execution-items:
        - BOW
        - CROSSBOW
        - WOODEN_SWORD
        - STONE_SWORD
        - IRON_SWORD
        - GOLDEN_SWORD
        - DIAMOND_SWORD
        - NETHERITE_SWORD
